### ISSUE TITLE
Syntax Highlighting?

### ISSUE THREAD

**Issue by escholtz** [valyala/quicktemplate#19]
Do you know if anyone has started adding syntax highlighting support for various text editors? My personal interest is for Sublime Text.

**Comment by escholtz** [comment]
Here is a syntax file I came up with for ST3. Requires GoSublime.
```yaml
%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: "QuickTemplate"
file_extensions:
  - qtpl
scope: source.qtpl
contexts:
  main:
    - include: scope:text.html.basic
    - match: "{%"
      push: "Packages/GoSublime/syntax/GoSublime-Go.tmLanguage"
      with_prototype:
        - match: "(?=%})"
          pop: true
        - match: "(code|elseif|endif|endfor|endfunc|comment|endcomment|plain|endplain|stripspace|endstripspace|collapsespace|endcollapsespace|endswitch)"
          scope: "keyword.other.go"
```

I'm a Sublime syntax newbie so probably lots of improvements to be made but the basics seem to work (highlighting html, go, and quicktemplate keywords all in the same file).
